apiVersion: v1
kind: Namespace
metadata:
  name: genai-ns

---
apiVersion: v1
kind: Service
metadata:
  annotations:
    Service.kubernetes.io/topology-aware-hints: auto
  name: genai-service
  namespace: genai-ns
  labels:
    app: genai
spec:
  selector:
    app: genai
  ports:
    - name: genai-port
      protocol: TCP
      port: 80
      targetPort: 8501
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: genai
  namespace: genai-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: genai
  nodeSelector:
    cloud.google.com/gke-accelerator: "nvidia-tesla-t4"
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: genai
    spec:
      containers:
      - name: genai
        image: "us-central1-docker.pkg.dev/stealth-air-23412/udp-repo/genai"
        ports:
          - containerPort: 8501
        resources:
          limits:
            nvidia.com/gpu: 1
          requests:
            cpu: "18"
            memory: "18Gi"
