apiVersion: v1
kind: Namespace
metadata:
  name: genai-ns

---
apiVersion: v1
kind: Service
metadata:
  name: genai-service
  namespace: genai-ns
  labels:
    app: genai
spec:
  selector:
    app: genai
  ports:
    - name: genai-port
      protocol: TCP
      port: 80
      targetPort: 8501
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: genai
  namespace: genai-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: genai
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: genai
    spec:
      nodeSelector:
        cloud.google.com/gke-accelerator: "nvidia-tesla-t4"
      containers:
      - name: genai
        image: "${ARTIFACT_REPO_REGION}-docker.pkg.dev/${GCP_PROJECT_ID}/${ARTIFACT_REPO_NAME}/genai"
        ports:
          - containerPort: 8501
        resources:
          limits:
            nvidia.com/gpu: 1
            ephemeral-storage: 15Gi
          requests:
            cpu: "8"
            memory: "8Gi"
